#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P) 
source ${DIR}/include.sh

function usage {
    echo "Encrypts the copied text with a random password"
    echo "USAGE: $(basename $0) [-e|-d]"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

case "$1" in
    '-d')
        MODE="decrypt"
        ;;
    '-e')
        MODE="encrypt"
        ;;
    *)
        usage
        ;;
esac

FILE="$2"

if [ "${MODE}" == "encrypt" ]; then
    PW=$(get_pw)
    pbpaste | gpg -c --batch --armor --passphrase "${PW}" 2>/dev/null
    echo ""
    echo "P/W: ${PW}"
elif [ "${MODE}" == "decrypt" ]; then
    MSG=$(pbpaste)
    read -p "P/W: " PW
    echo "***"
    echo "${MSG}" | gpg -d --batch --armor --passphrase "${PW}" 2>/dev/null
    echo ""
    echo "***"
fi

exit 0
